In [1]:
import numpy as np

In [2]:
x = [2, 3, 4, 5, 6]
type(x)

list

In [3]:
nums = np.array(x)
type(nums)

numpy.ndarray

In [4]:
nums = np.array([[2, 4, 6], [8, 10, 12], [14, 16, 18]])
nums

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [6]:
nums = np.arange(2, 7)
nums

array([2, 3, 4, 5, 6])

In [7]:
nums = np.arange(2, 7, 2)
nums

array([2, 4, 6])

In [11]:
nums = np.zeros((5, 4))
nums

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
nums = np.ones((5, 4))
nums

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [15]:
lin = np.linspace(1, 10, 20)
lin

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [17]:
idn = np.eye(4, 5)
idn

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [18]:
random = np.random.rand(2, 3)
random

array([[0.87166659, 0.74739575, 0.36256904],
       [0.61177176, 0.73272963, 0.50604819]])

In [20]:
random = np.random.randint(50, 100, 5)
random

array([58, 68, 81, 88, 84])

In [30]:
nums = np.arange(1, 17)
nums2 = nums.reshape((4, 4))
nums2
nums1 = nums2.reshape(16, 1)
nums1

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16]])

In [34]:
nums = np.arange(1, 17)
xmin = nums.argmin()
xmin

0

In [35]:
nums = np.arange(1, 17)
xmax = nums.argmax()
xmax

15

In [38]:
nums = np.arange(1, 16)
slice1 = nums[:10]
slice1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
nums = np.arange(1, 16)
slice1 = nums[::-1]
slice1

array([15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [41]:
nums = np.arange(1, 16)
nums2 = nums + 5
nums2

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [42]:
new_nums = nums + nums2
new_nums

array([ 7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35])